[[entries]]
key = "system-contract-registry-0000000000000000000000000000000000000000000000000000000000000000"
value = "AL0AAAAEAAAABwAAAGF1Y3Rpb26T2SPjNrIKTEyhTVkrYOW9P+Mwd1YYKQEE+b6zJtt64g4AAABoYW5kbGUgcGF5bWVudIz15Kz1H1TrWSkVmRh4ONw7wjQInEb8bKitF+dirkQBBAAAAG1pbnQBDD/oG3uGLlDHfvmpWKBb+phETyb5byPTehPJYkTPtxAAAABzdGFuZGFyZCBwYXltZW50DJlsEVBEcah+RVry6GsqXt1BZJm2P3gnDniX/qvJWMYRCg8gAAAA"

